### ISSUE TITLE
dpp usage in gemm?

### ISSUE THREAD

**Issue by joye** [adityaatluri/gemm-vega64#1]
@adityaatluri  I cannot understand sgemm_v13.cpp which uses dpp function.
https://github.com/adityaatluri/gemm-vega64/blob/master/sgemm_v13.cpp#L61
```cpp
    ldsReadA = redA+ty*16;
    ldsReadB = redB+(tx%2)*16 + (tx/2);
```

if the data in memory is v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, while each one is a float data; 
for ldsReadB, 
tx = 0, will load v0, v1, v2, v3;
tx = 1, will load v4, v5, v6, v7;
tx = 2, will load v1, v2, v3, v4; 

is this function wrong?

https://github.com/adityaatluri/gemm-vega64/blob/master/sgemm_v13.cpp#L99

in dpp_helper.h function, 
```cpp
inline void __device__ shared_read_b128(Float4 &a0, Float4 &a1, Float4 &b, unsigned ldsReadA, unsigned ldsReadB) {
    if(off == 0) {
        asm volatile("\n\
        ds_read_b128 %0, %3 offset:0 \n\
        ds_read_b128 %1, %4 offset:0 \n\
        ds_read_b128 %2, %4 offset:256 \n\
        "
        :"=v"(b),"=v"(a0),"=v"(a1)
        :"v"(ldsReadA),"v"(ldsReadB)
        );
```

from ldsReadA will load to b, and from ldsReadB will load to a0 and a1, is this function wrong?

**Comment by aditya4d** [comment]
I am not clear about the question you are asking.
The goal of using dpp is to reduce the number of `lds_read` instructions. The way it is implemented right now, each thread holds a 2x2 of 4x4s. And threads in a quad can share their B matrix. So, each thread loads unique 8x1 from lds. You can see it as for non-dpp version, to load 1 8x1s (shared between 4 threads), you dispatch 4 lds_read instructions (one per thread). For dpp version, to load 1 8x1s (shared between 4 threads), you dispatch 1 lds_read instruction (per unique thread). I hope the explanation makes it clear. I have plans to write documentation about it. Let me know if you are interested.

I have written about the optimization here: https://adityaatluri.github.io/2018/04/29/decreasing-lds-memory-requests.html

**Comment by joye** [comment]
Please correct me if my understanding is wrong, each threadblock (blockDim = 16 x 16 ) work on 128 x 128 data block; which uses Scott Gray's SGEMM method; 

in the no dpp version for example, in sgemm_v10.cpp, each thread for A you load 2 float4 data, for B also load 2 float4 data; just as Scott Gray in the SGEMM wiki said, and then do the mac operation.

Now for dpp version, for the code;

```
 inline void __device__ shared_read_b128(Float4 &a0, Float4 &a1, Float4 &b, unsigned ldsReadA, unsigned ldsReadB) {
     if(off == 0) {
        asm volatile("\n\
        ds_read_b128 %0, %3 offset:0 \n\
        ds_read_b128 %1, %4 offset:0 \n\
        ds_read_b128 %2, %4 offset:256 \n\
        "
        :"=v"(b),"=v"(a0),"=v"(a1)
        :"v"(ldsReadA),"v"(ldsReadB)
  );
```

ldsReadA will read to b, for the name I think from ldsReadA address will read to a0 or a1; and ldsReadB will read to b; so I think the code is wrong.

for 16 * 16 threads;
each thread load 2 float4 for A, 2 float4 for B; so the whole 16*16 threads,
A will load from lds to register with 32 float4,   B will also load from lds to register with 32 float4;   which is in no-dpp version code;

```
    ds_read_b128 %0, %4 offset:0 \n \
    ds_read_b128 %1, %4 offset:256 \n \
    ds_read_b128 %2, %5 offset:0 \n \
    ds_read_b128 %3, %5 offset:256 \n \
```

and if each thread load 1 float4 data for b; and the ldsReadB's calculation is ldsReadB = redB+(tx%2)*16 + (tx/2); just use tx which range from 0 to 15; only load 16 float4.

**Comment by aditya4d** [comment]
Right. I think the hardware should have to feature of broadcasting loaded data to threads if multiple threads access same LDS address. This saves access to LDS SRAM
I correct myself with previous explanation. The version `_v13.cpp` is x2 version, which means the sharing between 2 threads. I think I lost the x4 version where sharing happens between 4 threads.
I don't think it is hard to get the x4 version working.
Change ldsReadB to `ldsReadB = redB + (tx % 4) * 16 + (tx / 4)`
You also have to create new https://github.com/adityaatluri/gemm-vega64/blob/master/dpp_helper.h#L88
with 
```
    v_mac_f32_dpp %0, %8, %9 quad_perm:[0,0,0,0] \n\
    v_mac_f32_dpp %1, %8, %10 quad_perm:[0,0,0,0] \n\
    v_mac_f32_dpp %2, %8, %11 quad_perm:[0,0,0,0] \n\
    v_mac_f32_dpp %3, %8, %12 quad_perm:[0,0,0,0] \n\
    \
    v_mac_f32_dpp %4, %8, %9 quad_perm:[1,1,1,1] \n\
    v_mac_f32_dpp %5, %8, %10 quad_perm:[1,1,1,1] \n\
    v_mac_f32_dpp %6, %8, %11 quad_perm:[1,1,1,1] \n\
    v_mac_f32_dpp %7, %8, %12 quad_perm:[1,1,1,1] \n\
    \
    v_mac_f32_dpp %4, %8, %9 quad_perm:[2,2,2,2] \n\
    v_mac_f32_dpp %5, %8, %10 quad_perm:[2,2,2,2] \n\
    v_mac_f32_dpp %6, %8, %11 quad_perm:[2,2,2,2] \n\
    v_mac_f32_dpp %7, %8, %12 quad_perm:[2,2,2,2] \n\
    \
    v_mac_f32_dpp %4, %8, %9 quad_perm:[3,3,3,3] \n\
    v_mac_f32_dpp %5, %8, %10 quad_perm:[3,3,3,3] \n\
    v_mac_f32_dpp %6, %8, %11 quad_perm:[3,3,3,3] \n\
    v_mac_f32_dpp %7, %8, %12 quad_perm:[3,3,3,3] \n\
    "
```

**Comment by aditya4d** [comment]
Yes. Good catch. Swap `ldsReadA` and `ldsReadB`

**Comment by joye** [comment]
ldsReadB = redB + (tx % 4) * 16 + (tx / 4)  this still has some problem; first ldsReadB in your code should be byte offset;  but right now you seems used it as a float4 offset. And I still cannot understand the dpp usage in gemm, compared to no dpp version which load 32 float4 data for a and 32 float4 data for b, for dpp you only load 32 float4 data for a and 16 float4 data for b; what about another 16 float4 data for b?

**Comment by aditya4d** [comment]
As I mentioned in my previous comment, we issue 32 lds read instructions but only quarter of them gets fetched from SRAM. One fetch from SRAM gets broadcasted to 4 consecutive threads

**Comment by aditya4d** [comment]
I'll figure out proper mapping and let you know. I need to draw everything out to refresh my memory

**Comment by joye** [comment]
I think I know your dpp method in gemm, but the code doesn't match my understanding, use Scott's SGEMM wiki, I draw a simple pic;
  |  |  |  | 
| ----:| ----: | :----: |
| tid0| tid16 | tid32  |
| tid1| tid17  | tid33  |
| tid2| tid18  | tid34  |
| tid3| tid19  | tid35  |
| tid4| tid20  |tid36 |
| tid5| tid21  | tid37  |
| tid6| tid22  | tid38  |
| tid7| tid23  | tid39  |
| tid8| tid24  | tid40 |
| tid9| tid25  |tid41 |
| tid10| tid26  | tid42  |
| tid11| tid27  | tid43  |
| tid12| tid28  | tid44  |
| tid13| tid29  | tid45  |
| tid14| tid30  |tid46 |
| tid15| tid31  | tid47 |
| tid0| tid16 | tid32  |
| tid1| tid17  | tid33  |
| tid2| tid18  | tid34  |
| tid3| tid19  | tid35  |
| tid4| tid20  |tid36 |
| tid5| tid21  | tid37  |
| tid6| tid22  | tid38  |
| tid7| tid23  | tid39  |
| tid8| tid24  | tid40 |
| tid9| tid25  |tid41 |
| tid10| tid26  | tid42  |
| tid11| tid27  | tid43  |
| tid12| tid28  | tid44  |
| tid13| tid29  | tid45  |
| tid14| tid30  |tid46 |
| tid15| tid31  | tid47 |

I only draw the first 3 column, each block will do a float4 and float4 mac operation;    for the dumplicate tid0 to tid15 in row twice as Scott's wiki said, A will load 2 float4; so tid0~15 will load 32 float4,  so for dpp, you reduce B load; for tid0 to tid3 can reuse tid0's B data, for tid4 to tid7 reuse tid4's data; and for the another 16 column float4 data need to be loaded for B, can use tid1, tid5 to load;
so the B load can be viewed as: 

- tid0, tid4, tid8, tid12 will load the first column;
- tid16, tid20, tid24, tid28 will load the second column;
 at the same time 
- tid1, tid5, tid9, tid13 will load the next 17th column,
etc;
and then can use dpp. Please correct me if my understanding is wrong.

**Comment by aditya4d** [comment]
Can you translate it to english?

**Comment by joye** [comment]
I mistakely updated, now please check it.

**Comment by aditya4d** [comment]
I have to revisit the mappings to give you a correct answer

**Comment by aditya4d** [comment]
![bitmap](https://user-images.githubusercontent.com/2188479/86482989-ed302e80-bd07-11ea-8e82-f5060aff04e6.png)
The image shows computation done by a single wavefront (64 x 64). Each box is 16B or float4

The threads along `ty` load the same data for all `tx`. I have to admit that the code I have written is incomplete.
I forgot to add code which sets execution mask `exec` to `0x1111111111111111` for 1 to 4 mapping or `0x5555555555555555` for 1 to 2 mapping for dpp before issuing `lds_read` instruction. You have to reset it back to `0xFFFFFFFFFFFFFFFF` after that.

**Comment by aditya4d** [comment]
An inline asm block like
```cpp
int lds_exec_mask_set = 0x1111111111111111;
int lds_exec_mask_reset = 0xFFFFFFFFFFFFFFFF;
asm volatile("\n\
  s_mov_b64 exec, %0\n\
  "
  :
  :"s"(lds_exec_mask_set)
);

// lds_read instructions here
asm volatile("\n\
  s_mov_b64 exec, %0\n\
  "
  :
  :"s"(lds_exec_mask_reset)
);
```
